apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    address: 192.168.0.216
    k0sApiPort: 9443
    port: 6443
    sans:
    - 192.168.0.216
    - 192.168.122.1
    - 172.21.0.1
    - 172.17.0.1
    - 172.23.0.1
    - 10.88.0.1
    - 10.244.0.1
    - 2601:646:4000:3060::be49
    - 2601:646:4000:3060:8b13:5b76:2703:28f
    - 2601:646:4000:3060:683c:7a51:eee8:2eb
    - fe80::1fbd:2949:a12e:cedf
    - fe80::42:d5ff:fe58:a84f
    - fe80::844c:59ff:fe46:20dc
    - fe80::20e5:9dff:fe7a:4698
    - fe80::f86c:22ff:feb0:59ac
    - fe80::b0d0:51ff:fe45:ce31
    - fe80::3cd5:9eff:fed1:5f72
    tunneledNetworkingMode: false
  controllerManager: {}
  extensions:
    helm:
      charts: null
      repositories: null
    storage:
      type: openebs_local_storage
  images:
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.24.5
      kubecontrollers:
        image: docker.io/calico/kube-controllers
        version: v3.24.5
      node:
        image: docker.io/calico/node
        version: v3.24.5
    coredns:
      image: docker.io/coredns/coredns
      version: 1.9.4
    default_pull_policy: IfNotPresent
    konnectivity:
      image: quay.io/k0sproject/apiserver-network-proxy-agent
      version: 0.0.32-k0s1
    kubeproxy:
      image: registry.k8s.io/kube-proxy
      version: v1.25.4
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.5.1
      cniInstaller:
        image: quay.io/k0sproject/cni-node
        version: 1.1.1-k0s.0
    metricsserver:
      image: registry.k8s.io/metrics-server/metrics-server
      version: v0.6.1
    pushgateway:
      image: quay.io/k0sproject/pushgateway-ttl
      version: edge@sha256:7031f6bf6c957e2fdb496161fe3bea0a5bde3de800deeba7b2155187196ecbd9
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    calico: null
    clusterDomain: cluster.local
    dualStack: {}
    kubeProxy:
      mode: iptables
    kuberouter:
      autoMTU: true
      hairpinMode: false
      metricsPort: 8080
      mtu: 0
      peerRouterASNs: ""
      peerRouterIPs: ""
    podCIDR: 10.244.0.0/16
    provider: kuberouter
    serviceCIDR: 10.96.0.0/12
  scheduler: {}
  storage:
    etcd:
      externalCluster: null
      peerAddress: 192.168.0.216
    type: etcd
  telemetry:
    enabled: true
status: {}
